version: '3.9'

services:
  db:
    image: postgres:13
    container_name: "ponpon_db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=technique


  adminer:
    image: adminer
    container_name: "ponpon_adminer"
    ports:
      - 8080:8080